version: '3.3'

services:
    wordpress:
        #image: wordpress
        build: Wordpress/
        links:
            - db:mysql
        restart: always
        ports:
            - 8080:80
        #volumes:
            #-.:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: example

    db:
        #restart: unless-stopped
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: example
