version: '3.3'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./wp-config.php:/var/www/html/wp-content.php
            - ./plugins:/var/www/html/wp-content/plugins
            - ./themes:/var/www/html/wp-content/themes
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: user1
            WORDPRESS_DB_PASSWORD: user1
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./wpTEST:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user1
            MYSQL_PASSWORD: user1
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes:
            - ./PHPSessions:/sessions
        ports:
            - 8081:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_HOST: db
